# Generated by Django 2.1.2 on 2018-10-27 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
                ('site', models.SmallIntegerField(choices=[(1, '淘宝'), (2, '京东'), (3, '苏宁易购')], default=1, verbose_name='站点')),
                ('code', models.SlugField(help_text='例如：淘口令', verbose_name='分享码')),
                ('text', models.TextField(blank=True, verbose_name='分享文案')),
                ('image', models.ImageField(upload_to='', verbose_name='分享图')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '联盟分享',
                'verbose_name_plural': '联盟分享',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='share',
            unique_together={('site', 'code')},
        ),
    ]
