# Generated by Django 2.1.2 on 2018-11-07 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unionbuy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='数据创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='数据更新时间')),
                ('third', models.SmallIntegerField(choices=[(1, '淘宝')], default=1, verbose_name='类型')),
                ('third_uid', models.IntegerField(verbose_name='第三方uid')),
                ('access_token', models.CharField(max_length=200, verbose_name='AccessToken')),
                ('expires_in', models.DateTimeField(verbose_name='过期时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '第三方认证',
                'verbose_name_plural': '第三方认证',
            },
        ),
        migrations.AlterUniqueTogether(
            name='thirdauth',
            unique_together={('third', 'third_uid')},
        ),
    ]
